# Site configuration
# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - garth-jekyll-theme.gemspec

# Installed Gems
plugins:
  - jekyll-paginate

# Pagination settings
paginate: 2
paginate_path: page:num

# Jekyll settings
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
timezone: Europe/London

# Collections
collections:
  posts:
    title: Plan Our Date
    output: true
    description: "A fun and interactive website to plan our perfect date!"

# Layout defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Site settings
encoding: utf-8
title: "Plan Our Date"
description: "A fun and interactive website to plan our perfect date!"
url: "https://NikhilSunka.github.io/Rosy"
baseurl: "/Rosy" # Set this to "/Rosy" if it's a project site
lang: en-GB

# Theme (comment out if causing issues)
theme: minima
